.TH SLIMCAT "1" "August 2020" "SLIM CAT 1.1.0" "User Commands"
.SH NAME
slimcat \- still concatenating files and printing on the standard output, just slimmer.
.SH SYNOPSIS
.B cat
[\fI\,OPTION\/\fR]... [\fI\,FILE\/\fR]...
.SH DESCRIPTION
.PP
This is a rewrite of GNU cat where the unused features are removed. The only option is -h for help and -u for unbuffered output.
.PP
We concatenate files(s) to standard output with less than 50 lines of code.
.PP
With no file, or when file is \-, read standard input.
.SH EXAMPLES
.TP
slimcat -h
Displays help.
.TP
slimcat -u
Tells the OS that we dont want a buffer (warning may be a lot slower with a large file).
.TP
slimcat x \- y
Output x's contents, then standard input, then y's contents.
.TP
slimcat
Copy standard input to standard output.
.SH "EXIT STATUS"
.TP
0
Exited Normally (Success).
.TP
1
Error opening file.
.TP
2
Unknown command line argument.
.TP
3
Error while writing.
.SH AUTHOR
Written by Adam McKenney
.SH "REPORTING BUGS"
See the offical repo: <https://github.com/mckenney5/slim-cat>
.SH COPYRIGHT
Copyright \(co 2021 Adam McKenney


Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.


See the license for more information.
<https://github.com/mckenney5/slim-cat/raw/master/LICENSE>.

.SH "POSIX"
See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/cat.html for more info on cat.
.SH "SEE ALSO"
\fBtac\fP(1)

